name: Build Test MacOS

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        
    - name: Install dependencies
      run: |
        brew install cmake ninja

    - name: Configure CMake
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release --verbose

    - name: Test Run
      run: |
        cd build
        ./test_project
        
    - name: Debug Info
      run: |
        echo "=== Build Directory Structure ==="
        ls -R build/
        
        echo "=== Static Libraries ==="
        find build -name "*.a"
        
        echo "=== Dynamic Libraries ==="
        find build -name "*.dylib"
        
        echo "=== Executables ==="
        find build -type f -perm +111
        
        echo "=== CMake Cache ==="
        cat build/CMakeCache.txt

    - name: Upload Build Info
      uses: actions/upload-artifact@v3
      with:
        name: build-info
        path: |
          build/CMakeCache.txt
          build/compile_commands.json
        retention-days: 7