name: Build Test MacOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        
    - name: Install dependencies
      run: |
        brew install cmake ninja

    - name: Configure CMake
      run: |
        cmake --preset macos-ci \
          -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cmake --build --preset macos-ci \
          --config Release \
          --verbose -- \
          ONLY_ACTIVE_ARCH=NO \
          -arch arm64 -arch x86_64

    - name: Test Run
      run: |
        cd build
        ./test_project
        
    - name: Debug Info
      run: |
        echo "=== Build Directory Structure ==="
        ls -R build/
        
        echo "=== Static Libraries ==="
        find build -name "*.a"
        
        echo "=== Dynamic Libraries ==="
        find build -name "*.dylib"